### ISSUE TITLE
The unary minus is removed in the pattern of case expressions

### ISSUE THREAD

**Issue by dplusic** [lspitzner/brittany#49] opened 2017-08-19 17:59 UTC
input:
```haskell
module Main where
foo n = case n of
  1 -> True
  -1 -> False
```

output:
```haskell
module Main where
foo n = case n of
  1 -> True
  1 -> False
```

**Comment by lspitzner** [comment] 2017-08-19 18:11
Thanks for reporting, I can reproduce and already see the cause - the minus is represented in the AST only as an annotation. Of course still an error on brittany's end. I'll fix this later.

**Comment by lspitzner** [comment] 2017-08-19 21:50
@dplusic 
The fix is not as easy as I had hoped because .. technical details. I have to contact the ghc-exactprint maintainers to ~~put the blame on them~~ see if there is chance to improve the interface so this is not as cumbersome to fix on brittany's end.

I discovered a workaround: Enable -XNegativeLiterals (just in the brittany config, your code can stay the same).

I could fix just this particular instance of this bug relatively quickly, but then it would reappear when the negative literals appeared in some nested position in a pattern, so that's no good.

**Comment by lspitzner** [comment] 2017-08-19 22:35
Nevermind, the fix turned out even easier than I had initially assumed. I just had to read the ghc sourcecode to make sense of its API. Fixed on `dev` branch.

**Comment by dplusic** [comment] 2017-08-21 03:58
I checked fixed on `dev`. Thanks!

**Closed** 2017-09-26 21:31 UTC
Labels: fixed in HEAD
