### ISSUE TITLE
lenses

### ISSUE THREAD

**Issue by awalterschulze** [lspitzner/brittany#182] opened 2018-09-14 12:50 UTC
I just want to check whether this is intended.
I am using proto-lens to build some tests for protobufs.

Here is what the code looked like before formatting, which I found was quite readable, unlike most of my haskell code, which brittany always improves.

```haskell
examplePerson :: D.DescriptorProto
examplePerson = def
    & D.name .~ "Person"
    & D.field .~ [
        def
        & D.name .~ "Name"
        & D.number .~ 1
        & D.label .~ D.FieldDescriptorProto'LABEL_OPTIONAL
        & D.type' .~ D.FieldDescriptorProto'TYPE_STRING
        , def
        & D.name .~ "Address"
        & D.number .~ 2
        & D.label .~ D.FieldDescriptorProto'LABEL_OPTIONAL
        & D.type' .~ D.FieldDescriptorProto'TYPE_MESSAGE
        & D.typeName .~ ".person.Person.Address"
        , def
        & D.name .~ "PhoneNumbers"
        & D.number .~ 3
        & D.label .~ D.FieldDescriptorProto'LABEL_REPEATED
        & D.type' .~ D.FieldDescriptorProto'TYPE_MESSAGE
        & D.typeName .~ ".phone.PhoneNumber"
    ]
    & D.nestedType .~ [
        exampleAddress
    ]
```

Brittany formatted the code to look like the following.
Is this intended?

```haskell
examplePerson :: D.DescriptorProto
examplePerson =
  def
    &  D.name
    .~ "Person"
    &  D.field
    .~ [ def
       &  D.name
       .~ "Name"
       &  D.number
       .~ 1
       &  D.label
       .~ D.FieldDescriptorProto'LABEL_OPTIONAL
       &  D.type'
       .~ D.FieldDescriptorProto'TYPE_STRING
       , def
       &  D.name
       .~ "Address"
       &  D.number
       .~ 2
       &  D.label
       .~ D.FieldDescriptorProto'LABEL_OPTIONAL
       &  D.type'
       .~ D.FieldDescriptorProto'TYPE_MESSAGE
       &  D.typeName
       .~ ".person.Person.Address"
       , def
       &  D.name
       .~ "PhoneNumbers"
       &  D.number
       .~ 3
       &  D.label
       .~ D.FieldDescriptorProto'LABEL_REPEATED
       &  D.type'
       .~ D.FieldDescriptorProto'TYPE_MESSAGE
       &  D.typeName
       .~ ".phone.PhoneNumber"
       ]
    &  D.nestedType
    .~ [exampleAddress]
```

**Comment by lspitzner** [comment] 2018-09-14 16:11
Duplicate of #79 and #149. I agree this is far from optimal, and the workaround of adding parentheses is not satisfactory. Unfortunately nobody has put in the time to implement #79 yet.

**Closed by lspitzner** 2018-09-14 16:11 UTC

**Comment by awalterschulze** [comment] 2018-09-14 16:35
Oh ok awesome, so I can already fix this with parenthesis

```haskell
examplePersonDesc :: D.DescriptorProto
examplePersonDesc =
  def
    &  (D.name .~ "Person")
    &  D.field
    .~ [ def
       & (D.name .~ "Name")
       & (D.number .~ 1)
       & (D.label .~ D.FieldDescriptorProto'LABEL_OPTIONAL)
       & (D.type' .~ D.FieldDescriptorProto'TYPE_STRING)
       , def
       & (D.name .~ "Address")
       & (D.number .~ 2)
       & (D.label .~ D.FieldDescriptorProto'LABEL_OPTIONAL)
       & (D.type' .~ D.FieldDescriptorProto'TYPE_MESSAGE)
       & (D.typeName .~ ".person.Person.PersonAddress")
       , def
       & (D.name .~ "PhoneNumbers")
       & (D.number .~ 3)
       & (D.label .~ D.FieldDescriptorProto'LABEL_REPEATED)
       & (D.type' .~ D.FieldDescriptorProto'TYPE_MESSAGE)
       & (D.typeName .~ ".phone.PhoneNumber")
       ]
    &  (D.nestedType .~ [exampleAddressDesc])
```

Thank you so much :)
