### ISSUE TITLE
TH code is not supported?

### ISSUE THREAD

**Issue by pythonissam** [lspitzner/brittany#139] opened 2018-04-22 08:18 UTC
When we try to format code which includes TH:

```haskell
{-# LANGUAGE QuasiQuotes #-}
import Data.Yaml.TH

value :: Value
value = [yamlQQ|
name: John Doe
age: 23
|]
```

we get:

```bash
$ brittany A.hs
ERROR: brittany pretty printer returned syntactically invalid result.
ERROR: encountered unknown syntactical constructs:
HsSpliceE{}
```

Is this by design?

**Comment by lspitzner** [comment] 2018-04-22 14:09
No, TH is not supported yet. It may work for single-line cases because of tricky workarounds but those cannot made work reliably for multiline uses.

Two paths forward: Either someone implements the corresponding case (`HsSpliceE` in `Language.Haskell.Brittany.Internal.Layouters.Expr`) or, with the new inline-config feature (on branch master), you can disable brittany selectively (for the `value` sig/equation in this case):

~~~~.hs
-- brittany-disable-next-binding
value :: Value
value = [yamlQQ|
name: John Doe
age: 23
|]

otherFunc = still formatted
~~~~

Closing as duplicate of #90.

**Closed by lspitzner** 2018-04-22 14:09 UTC
