### ISSUE TITLE
Cannot install with ``cabal new-install``

### ISSUE THREAD

**Issue by kozross** [lspitzner/brittany#200] opened 2018-11-14 22:12 UTC
I used ``cabal new-install brittany``, which built and symlinked successfully. However, upon inspection, the symlink installed in ``.cabal/bin`` is broken. Specifically:

```
[koz@Sebastian ~]$ ls -l .cabal/bin/brittany 
lrwxrwxrwx 1 koz koz 114 Nov 15 11:07 .cabal/bin/brittany -> ../store/ghc-8.4.4/brittany-0.11.0.0-0a8c9349d1542d5ec4d9fa7e04ddc306a0d0258588195a4c6ed6da16fb792f41/bin/brittany
[koz@Sebastian ~]$ ls -l .cabal/store/ghc-8.4.4/brittany-0.11.0.0-76e40c3851b5f7f9fc85c22c6053d9db9be484aae20dc07bcef0955f0b6ac8df/
total 12
-rw-r--r-- 1 koz koz 2024 Nov 14 21:24 cabal-hash.txt
drwxr-xr-x 4 koz koz 4096 Nov 14 21:24 lib
drwxr-xr-x 3 koz koz 4096 Nov 14 21:24 share
```

**Comment by lspitzner** [comment] 2018-11-29 23:30
Duplicate of #162. See there.

**Closed by lspitzner** 2018-11-29 23:30 UTC
