### ISSUE TITLE
Feature: standard-alignement of entire structure

### ISSUE THREAD

**Issue by clojj** [lspitzner/brittany#195] opened 2018-11-01 16:50 UTC
Would it be possible, to align the _entire_ record at the '{' and not just line 9 (in this case)
![format](https://user-images.githubusercontent.com/4367963/47866279-99689600-ddfe-11e8-85c0-ebc1bb45b645.png)

..so to immediately get this
![format-all](https://user-images.githubusercontent.com/4367963/47866322-bb621880-ddfe-11e8-8792-4573fdb06ed4.png)

**Comment by tfausak** [comment] 2019-06-18 02:24
I think this is a duplicate of #47 because Brittany doesn't currently format data declarations at all. Please reopen if that's not the case!

**Closed by tfausak** 2019-06-18 02:24 UTC
Labels: duplicate
