### ISSUE TITLE
allow to hang closing paren/brace/bracket when possible

### ISSUE THREAD

**Issue by Pitometsu** [lspitzner/brittany#308] opened 2020-06-30 08:11 UTC
```hs
Type
  { field
  , field2 :: Int }
-- but
Type
  { field
  , field2 :: Int
  } deriving Generics

[ a
, b
, c ]
-- but
[ a
, b
, c
] ++ [d]
```
Or even without newline before closing paren at all.

**Comment by tfausak** [comment] 2020-07-21 12:11
I'm not quite sure what you're asking. What behavior do you currently see and what would you like to see instead?

**Comment by Pitometsu** [comment] 2020-07-21 14:19
I see no configuration option to keep a closing parens on same line (kinda lisp style).

**Comment by tfausak** [comment] 2020-12-11 17:32
I think this is a duplicate of #157.

**Closed by tfausak** 2020-12-11 17:32 UTC
Labels: enhancement, hs:brackets
