### ISSUE TITLE
Failing on top level template haskell splices

### ISSUE THREAD

**Issue by eborden** [lspitzner/brittany#70] opened 2017-11-28 23:49 UTC
For some reason `brittany` is failing to print exact for top level
splices. This may be an issue in `brittany` or `ghc-exact-print`, I'm
not sure. I've added failing tests to highlight this issue. This bug
causes `brittany` to produce syntactically invalid Haskell.

```
1) template haskell top level splice
      expected: Right
                {-# LANGUAGE TemplateHaskell #-}
                deriveFromJSON (unPrefix "assignPost") ''AssignmentPost

      but got: Right
                {-# LANGUAGE TemplateHaskell #-}
                deriveFromJSON (unPrefix "assignPost") ''
```

**Comment by lspitzner** [comment] 2017-12-08 18:34
I have found the cause of this. The filtering of annotations per top-level decl throws away one annotation connected to the `Unqual` identifier that is in `''AssignmentPost`. I am a bit confused that this part of the syntax tree even _has_ an Annotation, because it cannot have an AnnKey.

I'll investigate this a bit more; however there already would be a brute-force fix: Don't filter annotation for externally-printed top-level decls.

**Comment by eborden** [comment] 2017-12-08 19:02
Oh awesome. I was just trying to repro this in `ghc-exactprint` the other night. :tada:

**Comment by lspitzner** [comment] 2017-12-08 19:04
Should be fixed. In theory this fix is a bit sloppy because we should calculate some transitive closure in `extractToplevelAnns`. But as rarely as `annCapturedSpan` seems to be used, I'll take that risk.

**Closed** 2017-12-08 20:27 UTC
Labels: fixed in HEAD
