### ISSUE TITLE
Parsing errors with Haddock

### ISSUE THREAD

**Issue by dschrempf** [lspitzner/brittany#281] opened 2020-02-13 17:35 UTC
Formatting of Haddock comments in the export list of module headers leads to semantic errors with Haddock. For example, the following code

    ( DataTypeI       
    , DataTypeII(DataConstructor)
      -- * Haddock heading
    , name
    )

is formatted by Brittany to

    ( DataTypeI
    , DataTypeII
      ( DataConstructor
        -- * Haddock heading
      )
    , name
    )

which throws a Haddock error of the form

    parse error on input ‘-- * Haddock heading’
    source  >    |      
    source  > 23 |     -- * Haddock heading
    source  >    |     ^^^^^^^^^^^^

See also issue #231.

**Comment by tfausak** [comment] 2020-07-21 13:14
I think this is a duplicate of #220.

**Closed by tfausak** 2020-07-21 13:14 UTC
Labels: bug, hs:comments
